@startuml
!include ./DesignPatterns/LinkedList.puml
!include ./DesignPatterns/CommandPattern.puml
!include ./DesignPatterns/Program.puml
!include ./DesignPatterns/Decorator/Pizza.puml
!include ./DesignPatterns/Decorator/TextEditor.puml
!include ./DesignPatterns/Decorator/NetworkExample.puml
!include ./DesignPatterns/Solid/interface-segregation-before.puml
!include ./DesignPatterns/Solid/open-closed.puml
!include ./DesignPatterns/Solid/liskov-substitution-before.puml
!include ./DesignPatterns/Solid/dependency-inversion-principle.puml
!include ./DesignPatterns/Solid/interface-segregation-using-composition-instead.puml
!include ./DesignPatterns/Solid/interface-segregation-after.puml
!include ./DesignPatterns/Solid/single-responsibility-before.puml
!include ./DesignPatterns/Solid/single-responsibility-after.puml
!include ./DesignPatterns/Solid/liskov-substitution-after.puml
!include ./DesignPatterns/ExpressionVisitor/Expression.puml
!include ./DesignPatterns/CompositeAndVisitor/ShipmentVisitor.puml
!include ./DesignPatterns/CompositeAndVisitor/SeedShipment.puml
!include ./DesignPatterns/CompositeAndVisitor/Shipment.puml
!include ./DesignPatterns/CompositeAndVisitor/ShipmentVisitorWithoutRecursion.puml
!include ./DesignPatterns/Strategy/Strategy.puml
!include ./DesignPatterns/Strategy/PersonWithFriends.puml
!include ./DesignPatterns/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./DesignPatterns/obj/Debug/net8.0/DesignPatterns.GlobalUsings.g.puml
!include ./DesignPatterns/obj/Debug/net8.0/DesignPatterns.AssemblyInfo.puml
@enduml
